### ISSUE TITLE
[Enhancement] Option to add the letter back on top of the improved icon

### ISSUE THREAD

**Issue by MiniSvamp** [Alphalaneous/Awesome-Modifier-Icons#1]
This would make it easier to learn the letters of the blocks, and make it easier to discuss with others the blocks if they don't use this mod, and also marking it visually when making a level using them.

**Comment by Alphalaneous** [comment]
This is already an option, check the mod settings

**Comment by Alphalaneous** [comment]
![image](https://github.com/user-attachments/assets/04898392-2751-42f8-89fa-4c172ea36b7f)
